settings:
  anchor: false
  html: false
  inject: true
  indent: 3
sort:
  enabled: true
  by: required

output:
  file: ./README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
